spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/shopping_cart_service_database
    username: postgres
    password: pasword
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /shopping-cart
  port: 8083

 rabbitmq:
     port: 5672
     host: rabbitmq
     username: guest
     password: guest
     listener:
       direct:
         default-requeue-rejected: true